Resources:
  InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.inputBucket}
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  OutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.outputBucket}
